### ISSUE TITLE
Error in output template: unsupported format character

### ISSUE THREAD

**Issue by snarfed** [snarfed/huffduff-video#14]
happens when the video title has a `%` in it. i think this is rg3/youtube-dl#5006 ?

example:

```
mod_wsgi (pid=10284): Exception occurred processing WSGI script '/var/www/cgi-bin/app.py'.,
  referer: http://www.polygon.com/a/2016-game-preview-100-games/introduction-and-video-special
Traceback (most recent call last):
  File "/var/www/cgi-bin/app.py", line 128, in run
    youtube_dl.YoutubeDL(options).download([url])
  File "/usr/local/lib/python2.6/site-packages/youtube_dl/YoutubeDL.py", line 1677, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/lib/python2.6/site-packages/youtube_dl/YoutubeDL.py", line 676, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
...
  File "/usr/local/lib/python2.6/site-packages/youtube_dl/YoutubeDL.py", line 589, in prepare_filename
    self.report_error('Error in output template: ' + str(err) + ' (encoding: ' + repr(preferredencoding()) + ')')
  File "/usr/local/lib/python2.6/site-packages/youtube_dl/YoutubeDL.py", line 540, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/lib/python2.6/site-packages/youtube_dl/YoutubeDL.py", line 510, in trouble
    raise DownloadError(message, exc_info)
DownloadError: ERROR: Error in output template: unsupported format character 'B' (0x42) at index 102 (encoding: 'ANSI_X3.4-1968')
```

**Comment by snarfed** [comment]
another example: https://www.oreilly.com/ideas/applications-of-ai-technologies-peter-norvig-in-conversation-with-tim-oreilly

```
DownloadError: ERROR: Error in output template: unsupported format character 'B' (0x42) at index 53 (encoding: 'ANSI_X3.4-1968')
```

**Comment by snarfed** [comment]
reported in https://github.com/rg3/youtube-dl/issues/5006#issuecomment-234045847
